# -*- coding: utf-8 -*-
"""DAY5_RAG_Anxiety detection through voice and text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZR7xBF9GFfgMtohBe7zxkq4muZBpCvRZ
"""

# ============================================================
# AI-BASED STUDENT ANXIETY DETECTION SYSTEM
# USING STUDENTLIFE DATASET + RAG + OLLAMA
# ============================================================

# ============================================================
# STEP 1 — INSTALL LIBRARIES
# ============================================================

!pip install -q langchain
!pip install -q langchain-community
!pip install -q langchain-huggingface
!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q ollama
!pip install -q pandas

# ============================================================
# STEP 2 — INSTALL & START OLLAMA
# ============================================================

# Install zstd dependency for Ollama
!apt-get update && apt-get install -y zstd

!curl -fsSL https://ollama.com/install.sh | sh

import subprocess
import time

subprocess.Popen(["ollama", "serve"])

time.sleep(5)

# ============================================================
# STEP 3 — DOWNLOAD MISTRAL MODEL
# ============================================================

!ollama pull mistral

# ============================================================
# STEP 4 — IMPORT LIBRARIES
# ============================================================

import pandas as pd

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

from langchain_community.llms import Ollama

from langchain_core.prompts import PromptTemplate

from langchain_classic.chains import RetrievalQA

# ============================================================
# STEP 5 — LOAD STUDENTLIFE DATASET
# ============================================================

# Upload your kaggle CSV file into colab first

# Unzip the dataset file
!unzip -o /content/archive.zip

# The original 'Stress_dataset.csv' was not found. Using 'PerceivedStressScale.csv' found in the unzipped archive.
df = pd.read_csv("dataset/survey/PerceivedStressScale.csv")

print(df.head())

print("\nColumns:")
print(df.columns)

# Define mapping for Likert scale responses to numerical values
score_mapping = {
    'Never': 0,
    'Almost never': 1,
    'Sometime': 2,
    'Fairly Often': 3,
    'Very Often': 4
}

# Questions that are reverse-scored (positively worded questions)
# According to PSS-10, these are typically questions 4, 5, 7, 8.
# The column names are long, so we'll use their 'numeric' index in a loop.
# Assuming columns are 1-indexed in the original questionnaire
reverse_score_cols = [
    '4. In the last month, how often have you felt confident about your ability to handle your personal problems?',
    '5. In the last month, how often have you felt that things were going your way?',
    '7. In the last month, how often have you been able to control irritations in your life?',
    '8. In the last month, how often have you felt that you were on top of things?'
]

# List of all PSS-10 question columns
pss_cols = [
    '1. In the last month, how often have you been upset because of something that happened unexpectedly?',
    '2. In the last month, how often have you felt that you were unable to control the important things in your life?',
    '3. In the last month, how often have you felt nervous and "stressed"?',
    '4. In the last month, how often have you felt confident about your ability to handle your personal problems?',
    '5. In the last month, how often have you felt that things were going your way?',
    '6. In the last month, how often have you found that you could not cope with all the things that you had to do?',
    '7. In the last month, how often have you been able to control irritations in your life?',
    '8. In the last month, how often have you felt that you were on top of things?',
    '9. In the last month, how often have you been angered because of things that were outside of your control?',
    '10. In the last month, how often have you felt difficulties were piling up so high that you could not overcome them?'
]

# Create new columns for numerical scores
for col in pss_cols:
    df[f'{col}_score'] = df[col].map(score_mapping)

# Apply reverse scoring for specified columns
for col in reverse_score_cols:
    df[f'{col}_score'] = 4 - df[f'{col}_score']

# Calculate Total PSS-10 Score
# Sum all the _score columns
score_columns = [f'{col}_score' for col in pss_cols]
df['PSS10_Total_Score'] = df[score_columns].sum(axis=1)

# Calculate PSS10_Avg (average score per item)
df['PSS10_Avg'] = df['PSS10_Total_Score'] / 10

# Categorize Stress Level based on PSS10_Total_Score
def categorize_stress_level(score):
    if score <= 13:
        return 'LOW'
    elif 14 <= score <= 26:
        return 'MODERATE'
    else:
        return 'HIGH'

df['StressLevel'] = df['PSS10_Total_Score'].apply(categorize_stress_level)

print("DataFrame with calculated PSS10_Avg and StressLevel:")
display(df[['uid', 'type', 'PSS10_Total_Score', 'PSS10_Avg', 'StressLevel']].head())

# ============================================================
# STEP 6 — CREATE DOCUMENTS
# ============================================================

documents = []

for i, row in df.iterrows():

    # Modify the text structure to reflect the columns in PerceivedStressScale.csv if needed
    # For simplicity, assuming these columns might relate to 'stress_level', 'mood' etc.
    # This part might need further adjustment based on the actual content of PerceivedStressScale.csv
    text = f"""
    Student's stress scale score is {row['PSS10_Avg']}.
    Student's stress level is {row['StressLevel']}.
    # Placeholder for other relevant columns if they exist in 'PerceivedStressScale.csv'
    """

    documents.append(text)

print("\nSample Document:")
print(documents[0])

# ============================================================
# STEP 7 — CHUNKING
# ============================================================

CHUNK_SIZE = 300
CHUNK_OVERLAP = 30

splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP
)

langchain_docs = []

for doc_index, doc_text in enumerate(documents):

    chunks = splitter.split_text(doc_text);

    for chunk_index, chunk_text in enumerate(chunks):

        langchain_docs.append(
            Document(
                page_content=chunk_text,
                metadata={
                    "doc_index": doc_index,
                    "chunk_index": chunk_index
                }
            )
        )

print("\nChunks Created:", len(langchain_docs))

# ============================================================
# STEP 8 — CREATE EMBEDDINGS
# ============================================================

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

embeddings = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL
)

# ============================================================
# STEP 9 — CREATE FAISS VECTOR STORE
# ============================================================

vectorstore = FAISS.from_documents(
    langchain_docs,
    embeddings
)

print("\nFAISS Vector Store Ready!")

# ============================================================
# STEP 10 — LOAD OLLAMA MODEL
# ============================================================

llm = Ollama(
    model="mistral",
    temperature=0.1,
    num_predict=300
)

print("\nLLM Ready!")

# ============================================================
# STEP 11 — CREATE PROMPT TEMPLATE
# ============================================================

PROMPT_TEMPLATE = """

YouAre an AI Mental Health Assistant.

Analyze the student's condition carefully.

Classify anxiety level into:
- LOW
- MODERATE
- HIGH

Also provide:
1. Reason
2. Recommendation

Use ONLY the provided context.

Context:
{context}

Question:
{question}

Answer:
"""

prompt_template = PromptTemplate(
    input_variables=["context", "question"],
    template=PROMPT_TEMPLATE
)

# ============================================================
# STEP 12 — CREATE RAG CHAIN
# ============================================================

retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 3}
)

ragn_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=retriever,
    return_source_documents=True,
    chain_type_kwargs={"prompt": prompt_template}
)

print("\nRAG Chain Ready!")

# ============================================================
# STEP 13 — TEST THE SYSTEM
# ============================================================

question = """
Student feels stressed about exams,
sleeping only 4 hours,
feeling mentally exhausted,
and unable to focus.
"""

result = rag_chain.invoke({"query": question})

# ============================================================
# STEP 14 — PRINT RESULT
# ============================================================

print("\n" + "="*60)
print("AI ANXIETY DETECTION RESULT")
print("="*60)

print("\nQUESTION:")
print(question)

print("\nANSWER:")
print(result["result"])

print("\nSOURCE DOCUMENTS:")

for i, doc in enumerate(result["source_documents"], 1):

    print(f"\n[{i}]")
    print(doc.page_content)

print("\n" + "="*60)
print("SYSTEM EXECUTED SUCCESSFULLY")
print("="*60)

"""The previous steps set up a RAG chain using the Ollama `mistral` model. To use the Gemini API with a RAG chain, we need to install the `langchain-google-genai` library, set up the API key, and then create a new RAG chain using `ChatGoogleGenerativeAI` as the LLM, reusing the existing `retriever` and `prompt_template`."""

import os
import google.generativeai as genai
from langchain_google_genai import ChatGoogleGenerativeAI

# Securely set your Google API Key
# It is strongly recommended to store your API key in Colab Secrets
# (click the '🔑' icon in the left panel) and name it 'GOOGLE_API_KEY'.
# Then, the code will automatically retrieve it.
# If you prefer to paste your key directly (not recommended for production),
# uncomment the line below and replace 'YOUR_API_KEY_HERE' with your actual key.

GOOGLE_API_KEY = None
try:
    from google.colab import userdata
    # Corrected: Get the secret named 'GOOGLE_API_KEY'
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
except ImportError:
    # Not in Colab, try environment variable
    GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')
except Exception as e:
    # Catch SecretNotFoundError and other potential issues when accessing userdata
    print(f"Could not retrieve GOOGLE_API_KEY from Colab secrets: {e}")
    GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')

# Fallback if no key found from secrets or env variable
# If you uncomment this line, replace 'YOUR_API_KEY_HERE' with your key
GOOGLE_API_KEY = "AIzaSyDT3_CQ61iAjcQmXetXy3MZRMr1hAnlQ60"

if not GOOGLE_API_KEY:
    raise ValueError("GOOGLE_API_KEY not found. Please set it in Colab Secrets or uncomment the direct assignment line with your key.")

genai.configure(api_key=GOOGLE_API_KEY)

print("Google Generative AI configured.")

# ==============================
# INSTALL REQUIRED LIBRARIES
# ==============================

!pip install -U langchain
!pip install -U langchain-community
!pip install -U langchain-google-genai
!pip install -U google-generativeai
!pip install -U faiss-cpu

# ==============================
# IMPORT LIBRARIES
# ==============================

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.chains.retrieval_qa.base import RetrievalQA
from langchain.prompts import PromptTemplate

# ==============================
# GEMINI API KEY
# ==============================

GOOGLE_API_KEY = "YOUR_GEMINI_API_KEY"

# ==============================
# PROMPT TEMPLATE
# ==============================

template = """
You are an AI assistant for Anxiety Detection.

Use the following context to answer the user's question.

Context:
{context}

Question:
{question}

Answer:
"""

prompt_template = PromptTemplate(
    template=template,
    input_variables=["context", "question"]
)

# ==============================
# INITIALIZE GEMINI MODEL
# ==============================

gemini_llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    temperature=0.1,
    google_api_key=GOOGLE_API_KEY
)

# ==============================
# CREATE RAG CHAIN
# ==============================

gemini_rag_chain = RetrievalQA.from_chain_type(
    llm=gemini_llm,
    chain_type="stuff",
    retriever=retriever,   # your existing retriever
    return_source_documents=True,
    chain_type_kwargs={"prompt": prompt_template}
)

print("Gemini RAG Chain Ready!")

# ==============================
# QUESTION
# ==============================

question = "What are symptoms of anxiety in university students?"

print("\n" + "="*60)
print("GEMINI AI ANXIETY DETECTION RESULT")
print("="*60)

print("\nQUESTION:")
print(question)

# ==============================
# RUN RAG SYSTEM
# ==============================

gemini_result = gemini_rag_chain.invoke({
    "query": question
})

# ==============================
# PRINT ANSWER
# ==============================

print("\nANSWER:")
print(gemini_result["result"])

# ==============================
# PRINT SOURCE DOCUMENTS
# ==============================

print("\nSOURCE DOCUMENTS:")

for i, doc in enumerate(gemini_result["source_documents"], 1):
    print(f"\n[{i}]")
    print(doc.page_content)

print("\n" + "="*60)
print("GEMINI SYSTEM EXECUTED SUCCESSFULLY")
print("="*60)

print("Listing available Gemini models:")
for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)

"""The `PerceivedStressScale.csv` contains individual responses to the PSS-10 survey. To create meaningful 'stress scale score' and 'stress level' features, we need to:

1.  Map the textual responses (e.g., 'Never', 'Fairly Often') to numerical scores.
2.  Apply reverse scoring to specific questions as per the PSS-10 methodology.
3.  Calculate the total PSS-10 score.
4.  Calculate the average PSS-10 score (`PSS10_Avg`).
5.  Categorize the `StressLevel` based on the total score.
"""

# Define mapping for Likert scale responses to numerical values
score_mapping = {
    'Never': 0,
    'Almost never': 1,
    'Sometime': 2,
    'Fairly Often': 3,
    'Very Often': 4
}

# Questions that are reverse-scored (positively worded questions)
# According to PSS-10, these are typically questions 4, 5, 7, 8.
# The column names are long, so we'll use their 'numeric' index in a loop.
# Assuming columns are 1-indexed in the original questionnaire
reverse_score_cols = [
    '4. In the last month, how often have you felt confident about your ability to handle your personal problems?',
    '5. In the last month, how often have you felt that things were going your way?',
    '7. In the last month, how often have you been able to control irritations in your life?',
    '8. In the last month, how often have you felt that you were on top of things?'
]

# List of all PSS-10 question columns
pss_cols = [
    '1. In the last month, how often have you been upset because of something that happened unexpectedly?',
    '2. In the last month, how often have you felt that you were unable to control the important things in your life?',
    '3. In the last month, how often have you felt nervous and "stressed"?',
    '4. In the last month, how often have you felt confident about your ability to handle your personal problems?',
    '5. In the last month, how often have you felt that things were going your way?',
    '6. In the last month, how often have you found that you could not cope with all the things that you had to do?',
    '7. In the last month, how often have you been able to control irritations in your life?',
    '8. In the last month, how often have you felt that you were on top of things?',
    '9. In the last month, how often have you been angered because of things that were outside of your control?',
    '10. In the last month, how often have you felt difficulties were piling up so high that you could not overcome them?'
]

# Create new columns for numerical scores
for col in pss_cols:
    df[f'{col}_score'] = df[col].map(score_mapping)

# Apply reverse scoring for specified columns
for col in reverse_score_cols:
    df[f'{col}_score'] = 4 - df[f'{col}_score']

# Calculate Total PSS-10 Score
# Sum all the _score columns
score_columns = [f'{col}_score' for col in pss_cols]
df['PSS10_Total_Score'] = df[score_columns].sum(axis=1)

# Calculate PSS10_Avg (average score per item)
df['PSS10_Avg'] = df['PSS10_Total_Score'] / 10

# Categorize Stress Level based on PSS10_Total_Score
def categorize_stress_level(score):
    if score <= 13:
        return 'LOW'
    elif 14 <= score <= 26:
        return 'MODERATE'
    else:
        return 'HIGH'

df['StressLevel'] = df['PSS10_Total_Score'].apply(categorize_stress_level)

print("DataFrame with calculated PSS10_Avg and StressLevel:")
display(df[['uid', 'type', 'PSS10_Total_Score', 'PSS10_Avg', 'StressLevel']].head())

"""Now that 'PSS10_Avg' and 'StressLevel' are calculated, we can modify the document creation step (STEP 6) to use these new columns, providing meaningful context for the RAG system."""